dist: bionic
sudo: true
language: cpp

install:
  - wget https://github.com/Kitware/CMake/releases/download/v3.17.2/cmake-3.17.2.tar.gz -O /tmp/cmake-3.17.2.tar.gz
  - tar -xvf /tmp/cmake-3.17.2.tar.gz
  - cd cmake-3.17.2 && ./bootstrap && make -j4 && sudo make install && cd ..

script:
  - cmake .
  - cmake --build . -- -j4
  - ctest -j4
