dist: bionic
sudo: true
language: cpp

before_install:
  - sudo apt-get update

addons:
  apt:
    packages:
      - g++-8
  snaps:
    - name: cmake
      confinement: classic

before_script:
  - ln -s /snap/cmake/current/bin/* /usr/bin/

script:
  - cmake .
  - cmake --build . -- -j2
  - ctest -j2
