dist: bionic
sudo: true
language: cpp

before_install:
  - sudo apt-get update

addons:
  apt:
    packages:
      - g++-8
  snaps:
    - cmake

script:
  - cmake .
  - cmake --build . -- -j2
  - ctest -j2
