#!/bin/sh

echo "[git][pre-commit] Running pre-commit hook..."

# =============================================================================
# 1. Run Cmake
# =============================================================================

CMAKE_BINARY_DIR=build/CI
CMAKE_BUILD_TYPE=Release

cmake -S . -B $CMAKE_BINARY_DIR -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DBENCHMARK_ENABLE_GTEST_TESTS=FALSE -DBENCHMARK_ENABLE_TESTING=FALSE -DCMAKE_CROSSCOMPILING=1 -DRUN_HAVE_STD_REGEX=0 -DRUN_HAVE_POSIX_REGEX=0 && cmake --build $CMAKE_BINARY_DIR --config $CMAKE_BUILD_TYPE --clean-first  --parallel 6 &&
    ctest --test-dir $CMAKE_BINARY_DIR -C $CMAKE_BUILD_TYPE && echo "SUCCESS" && exit 0

exit 1
